# Generated by Django 4.0.4 on 2022-04-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Fruit', 'fruit'), ('Vegetable', 'vegetable'), ('Greens', 'greens'), ('Spices', 'spices')], default='fruit', max_length=10)),
                ('image', models.ImageField(upload_to='catagory/')),
                ('descreption', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('descreption', models.CharField(max_length=255, null=True)),
                ('rating', models.FloatField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('order_amount', models.IntegerField()),
                ('catagory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
