# Generated by Django 4.0.4 on 2022-04-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('dona', 'one'), ('quti', 'box'), ('kilogramm', 'kilogram'), ('pachka', 'pack')], default='kilogram', max_length=10),
        ),
    ]
