# Generated by Django 4.0.4 on 2022-04-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_user_id_orderlist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
