# Generated by Django 4.0.4 on 2022-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
