# Generated by Django 4.0.4 on 2022-05-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_payment_orderlist_total_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='total_payment',
        ),
    ]
